export const personalData = {
  firstName: "Nipun",
  lastName: "Sathsara Basnayake",
  fullName: "Nipun Sathsara Basnayake",
  age: 25,
  illustration : "public/assets/images/photos/profile_Illustration.png",
  profilePic: "public/assets/images/photos/ProfilePic.jpg",
  location: "Negombo, Sri Lanka",
  email: "nipunsathsara1999@gmail.com",
  phone: "+94 77 880 6029",
  education: "UCSC Undergraduate | Software Engineering Intern",
  bio: "Hi, I'm Nipun Sathsara Basnayake, a passionate 25-year-old Software Engineering Intern from Negombo, Sri Lanka. I am currently pursuing my Bachelor's degree in Information Technology at the University of Colombo School of Computing (UCSC). With hands-on internship experience and a keen interest in developing innovative software solutions, I aim to blend creativity and technical expertise to build impactful applications.",
  socialLinks: {
    github: "https://github.com/NipunBasnayake",
    linkedin: "https://www.linkedin.com/in/nipunbasnayake/",
    facebook: "https://www.facebook.com/nipun.s99?mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/nipun__s/",
    whatsapp: "https://wa.me/94778806029",
  },
  roles: [
    "Software Engineering Intern",
    "Full Stack Developer",
    "Java Developer",
    "React Developer",
    "Angular Developer",
    "Spring Boot Developer",
    "Problem Solver",
  ],
  experience: "2+",
};

export const mainSkillAreas = [
  {
    title: "Frontend Development",
    icon: "Monitor",
    description:
      "Crafting responsive, accessible, and visually engaging user interfaces using modern frameworks and libraries.",
    skills: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Angular",
      "Bootstrap",
      "Tailwind CSS",
      "TypeScript",
      "SASS",
      "jQuery",
      "Figma",
    ],
  },
  {
    title: "Backend & Databases",
    icon: "Server",
    description:
      "Building robust backend systems and managing relational and NoSQL databases for scalable applications.",
    skills: [
      "Java",
      "Spring Boot",
      "PHP",
      "Node.js",
      "Python",
      "RESTful APIs",
      "JPA",
      "Hibernate",
      "MySQL",
      "MongoDB",
      "SQL",
    ],
  },
  {
    title: "Mobile & Cloud Technologies",
    icon: "Smartphone",
    description:
      "Developing mobile applications and integrating cloud-based services for seamless, real-time access.",
    skills: [
      "Android Studio",
      "React Native",
      "Firebase",
      "Git",
      "Docker",
      "AWS",
      "Kotlin",
      "CI/CD",
      "REST APIs",
    ],
  },
  {
    title: "Tools & Methodologies",
    icon: "Settings",
    description:
      "Applying agile workflows and leveraging modern tools to streamline development and collaboration.",
    skills: [
      "Postman",
      "Agile Methodology",
      "JIRA",
      "VS Code",
      "IntelliJ IDEA",
      "GitHub",
      "Trello",
      "Maven",
      "Scrum",
    ],
  },
];

export const projectsData = [
  {
    title: "HR Management System",
    description: "Full-featured HR system with secure login and Angular Material UI.",
    image: "public/assets/images/projects/hrmanagement.webp",
    tags: ["Spring Boot", "JPA", "Angular", "Angular Material"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/HrManagementSystem-Angular-Springboot",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Task Manager Application",
    description: "Full-stack task manager app with JWT authentication and Docker.",
    image: "public/assets/images/projects/taskmanager.webp",
    tags: ["Spring Boot", "JPA", "Angular", "Docker"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/TaskManager-Angular-Springboot",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Java Microservices with Kafka",
    description: "Event-driven system with 3 microservices using Spring Boot.",
    image: "public/assets/images/projects/microservices.webp",
    tags: ["Spring Boot", "Apache Kafka", "Microservices", "Java"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/Java-Springboot-Microservices",
    category: "backend",
    featured: true,
    viewButton: false,
  },
  {
    title: "Digital Tug Of War Game",
    description: "Real-time multiplayer game using React and WebSocket.",
    image: "public/assets/images/projects/tugofwar.webp",
    tags: ["ReactJS", "Spring Boot", "WebSocket", "Java"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/Digital-Tug-Of-War-Game",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "MOS Burgers Ordering System",
    description: "Ordering system for MOS Burgers with REST APIs.",
    image: "public/assets/images/projects/mosburgers.webp",
    tags: ["Spring Boot", "JPA", "HTML", "Bootstrap"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/MOS_Burgers",
    category: "web",
    featured: true,
    viewButton: false,
  },
  {
    title: "Clothify Store POS System",
    description: "JavaFX-based POS system for clothing stores.",
    image: "public/assets/images/projects/clothify.webp",
    tags: ["JavaFX", "Hibernate", "Google Guice"],
    demoLink: "",
    codeLink: "https://github.com/NipunBasnayake/Clothify-Store-JavaFX",
    category: "desktop",
    featured: true,
    viewButton: false,
  },
  {
    title: "ChatterAI",
    description: "AI chatbot using Gemini AI with a modern UI.",
    image: "public/assets/images/projects/chatterai.webp",
    tags: ["HTML", "CSS", "JavaScript", "AI"],
    demoLink: "https://nipunbasnayake.github.io/ChatteraAI/",
    codeLink: "https://github.com/NipunBasnayake/ChatteraAI",
    category: "web",
    featured: true,
    viewButton: true,
  },
  {
    title: "Vehicle Service Management System",
    description: "Web app to manage vehicle services using PHP and MySQL.",
    image: "public/assets/images/projects/service.webp",
    tags: ["PHP", "JavaScript", "HTML", "MySQL"],
    demoLink: "https://nipunbasnayake.github.io/Vehicle-Service-Management-System/",
    codeLink: "https://github.com/NipunBasnayake/Vehicle-Service-Management-System",
    category: "web",
    featured: true,
    viewButton: true,
  },
  {
    title: "Checkmate 3D",
    description: "3D chess game using Three.js and Stockfish engine.",
    image: "public/assets/images/projects/checkmate3d.webp",
    tags: ["Three.js", "JavaScript", "3D Graphics", "WebGL"],
    demoLink: "https://nipunbasnayake.github.io/CheckMate3D",
    codeLink: "https://github.com/NipunBasnayake/CheckMate3D",
    category: "web",
    featured: true,
    viewButton: true,
  },
];

export const certificationsData = [
  {
    title: "Java Foundations Professional",
    issuer: "JetBrains | LinkedIn Learning",
    date: "April 2025",
    description: "Proven understanding of Java basics, OOP, and algorithms.",
    badge: "public/assets/images/certifications/Java Foundations Professional Certificate by JetBrains.webp",
    verificationLink: "https://www.linkedin.com/learning/certificates/e36c4c7cb4dce77da805f0a45442256721d076b9b6e5b9f5dd37e9a4cd7a9a1e?trk=share_certificate",
  },
  {
    title: "Docker Foundations Professional",
    issuer: "Docker | LinkedIn Learning",
    date: "May 2025",
    description: "Proven understanding of Docker basics and containerization.",
    badge: "public/assets/images/certifications/Docker Foundations Professional Certificate.png",
    verificationLink: "https://www.linkedin.com/learning/certificates/8cf1b85131850ea7862e9761743ee711aff4423ea1257463784dfc4d1796c4a6?trk=share_certificate",
  },
  {
    title: "Postman API Student Expert",
    issuer: "Postman",
    date: "March 2025",
    description: "Validated core API development skills using Postman tools.",
    badge: "public/assets/images/certifications/Postman API Fundamentals Student Expert.png",
    verificationLink: "https://badgr.com/public/assertions/hJhfByj9S0CU3CiR7zZvhg?identity__email=nipunsathsara1999@gmail.com",
  },
  {
    title: "Machine Learning with Python",
    issuer: "LinkedIn Learning",
    date: "May 2025",
    description: "Knowledge of machine learning concepts and algorithms.",
    badge: "public/assets/images/certifications/Machine Learning with Python Foundations.png",
    verificationLink: "https://www.linkedin.com/learning/certificates/20ffd5c690e3290fa914926a915d0e914240d0f88e40e77ce8b80807ae097367?trk=share_certificate",
  },
  {
    title: "Diploma in Information Technology",
    issuer: "University of Colombo",
    date: "August 2023",
    description: "Comprehensive diploma in computer science and programming.",
    badge: "public/assets/images/certifications/Information Technology Diploma by UCSC.png",
    verificationLink: "https://ucsc.cmb.ac.lk/verify/221479",
  },
  {
    title: "Fundamentals of Digital Marketing",
    issuer: "Google Digital Academy (Skillshop)",
    date: "June 2022",
    description: "Certified in SEO, SEM, email, and analytics by Google.",
    badge: "public/assets/images/certifications/Fundamentals of digital marketing.png",
    verificationLink: "https://skillshop.exceedlms.com/student/award/5KvDazd1zcyRjFMPnJDBFZdf",
  },
];

export const sectionsData = {
  hero: {
    subtitle: "Welcome to my portfolio",
    ctaButtons: [
      {
        text: "View My Work",
        link: "#projects",
        type: "primary",
      },
      {
        text: "Contact Me",
        link: "#contact",
        type: "outline",
      },
    ],
  },
  about: {
    title: "About Me",
    subtitle: "Software Engineering Intern | UCSC Undergraduate",
    ctaButtons: [
      {
        text: "Download CV",
        link: "/assets/cv/nipun_sathsara_resume.pdf",
        type: "primary",
        id: "download-cv",
      },
      {
        text: "Get In Touch",
        link: "#contact",
        type: "outline",
      },
    ],
  },
  skills: {
    title: "My Skills",
    subtitle: "A showcase of my technical expertise and proficiency",
  },
  projects: {
    title: "My Projects",
    subtitle: "Check out some of my recent work",
    categories: ["all", "web", "mobile", "desktop"],
  },
  certifications: {
    title: "Certifications",
    subtitle: "Professional certifications and achievements",
  },
  contact: {
    title: "Get In Touch",
    subtitle: "Feel free to contact me for any project or collaboration",
    heading: "Let's Talk",
    description:
      "Have a project in mind or want to collaborate? Reach out using any of the methods below.",
  },
};